/**
 * @wrathbench/sdk — the surface the model programs against.
 *
 * The SDK's public shape is part of the harness version (docs/ARCHITECTURE.md).
 * Adding to it is a minor bump; changing or removing anything exported here is
 * a major one and wants an ADR under docs/decisions/.
 */

export {
  connect,
  KNOWN_ERROR_CODES,
  TRAINER_SPELL_STATE,
  WrathClient,
  WrathRequestError,
  WrathTransportError,
} from "./client";
export type {
  BuySpellResult,
  ConnectOptions,
  DeleteCharacterOptions,
  ErrorCode,
  GuidArg,
  GuidOrUnit,
  KillResult,
  KillTargetOptions,
  KnownErrorCode,
  LearnTalentResult,
  RawActionResponse,
  LootOptions,
  LootResult,
  MovePoint,
  MoveResult,
  MoveToOptions,
  QuestAcceptResult,
  QuestOptions,
  QuestTurnInResult,
  StoredLootItem,
  TrainerListResult,
  TrainerOptions,
  TrainerSpell,
  WaitForChatOptions,
  WaitForNearbyOptions,
} from "./client";

export {
  EventStream,
  EventStreamClosedError,
  EventTimeoutError,
  STREAM_ERROR,
  STREAM_GAP,
} from "./events";
export type {
  EventByOpcode,
  EventStreamOptions,
  StreamErrorEvent,
  StreamEvent,
  StreamGapEvent,
  Unsubscribe,
  WaitForOptions,
} from "./events";

export { pointOf, questGiverStatusName, StateCache } from "./state";
export type {
  Anomaly,
  AuraEntry,
  BagContents,
  BagSlotItem,
  ChatEntry,
  CharacterSummary,
  CreatureInfo,
  GapRecord,
  Gauge,
  GossipMenu,
  GossipMenuOption,
  InventoryItem,
  ItemInfo,
  KnownSpell,
  SpellCooldown,
  TalentEntry,
  TalentState,
  Motion,
  NearbyObject,
  NotificationEntry,
  Observed,
  Point3,
  QuestCompletion,
  QuestGiverStatusName,
  QuestInfo,
  QuestLogEntry,
  QuestObjective,
  SelfState,
  StateCacheOptions,
  StateSeed,
  StateSnapshot,
  UnitFieldsState,
  UnitFilter,
  UnitPosition,
  UnitView,
  WorldPosition,
} from "./state";

export {
  guidKey,
  isDecodeError,
  isEvent,
  isKnownOpcode,
  isMoveOpcode,
  KNOWN_OPCODES,
  MOVE_OPCODES,
  MOVE_STATUSES,
  parseEventFrame,
  PROTOCOL_REVISION,
} from "./protocol";
export type {
  ActionRequest,
  ActionResponse,
  AttackerStateUpdateData,
  AttackStartData,
  AttackStopData,
  AuraData,
  AuraUpdateData,
  BuyFailedData,
  BuyItemData,
  CastFailedData,
  CharacterDeleteRequest,
  CharacterDeleteResponse,
  CharDeleteData,
  CorpseReclaimDelayData,
  CreateBlock,
  DeathReleaseLocData,
  EmptyData,
  GossipMessageData,
  GossipOption,
  InventoryChangeFailureData,
  ItemPushResultData,
  ItemQueryResponseData,
  LevelUpInfoData,
  ListInventoryData,
  LogXpGainData,
  LootItemData,
  LootMoneyNotifyData,
  LootRemovedData,
  LootReleaseResponseData,
  LootResponseData,
  MonsterMoveData,
  OfferedQuest,
  PeriodicAuraLogData,
  QuestGiverOfferRewardData,
  QuestGiverQuestCompleteData,
  QuestGiverQuestDetailsData,
  QuestGiverQuestFailedData,
  QuestGiverQuestListData,
  QuestGiverRequestItemsData,
  QuestGiverStatusData,
  QuestGiverStatusMultipleData,
  RawField,
  RawPayload,
  InitialSpellsData,
  SpellCooldownData,
  TalentsInfoData,
  QuestQueryResponseData,
  QuestRewardItem,
  QuestUpdateAddItemData,
  QuestUpdateAddKillData,
  QuestUpdateQuestIdData,
  SellItemData,
  SpellFailureData,
  SpellGoData,
  SpellStartData,
  TrainerBuyFailedData,
  TrainerBuySucceededData,
  TrainerListData,
  TrainerSpellData,
  VendorItem,
  CreateSessionRequest,
  CreatureQueryResponseData,
  DecodeErrorData,
  DeleteSessionRequest,
  DeleteSessionResponse,
  DestroyObjectData,
  ErrorBody,
  FaceResponse,
  GameEvent,
  GuidKey,
  GuidListBlock,
  HealthResponse,
  KnownEvent,
  KnownMoveStatus,
  KnownOpcode,
  MoveOpcode,
  MoveProgressData,
  MoveResultData,
  MoveStatus,
  MoveToResponse,
  MoveUpdateData,
  MovementBlock,
  PositionData,
  SessionResponse,
  UnknownEvent,
  UpdateBlock,
  UpdateFields,
  UpdateObjectData,
  ValuesBlock,
} from "./protocol";
